; Configuration PHP for docker

[PHP]
; Memory limit and file upload access timeouts
memory_limit = 256M
max_execution_time = 300
post_max_size = 50M
upload_max_filesize = 50M

; Errors display and reporting
display_errors = On
error_reporting = E_ALL

; Sessions
session.save_handler = files
session.save_path = "/tmp"
session.gc_maxlifetime = 1440

; Timezone
date.timezone = Europe/Paris

; OPcache is a caching engine for PHP that improves performance by storing precompiled script bytecode in shared memory, thus eliminating the need for PHP to load and parse scripts on each request
;The following settings enable and configure OPcache:
opcache.enable = 1
opcache.memory_consumption = 128
opcache.max_accelerated_files = 4000
opcache.revalidate_freq = 2

Extensions
extension = pdo_mysql
extension = mysqli
extension = gd
extension = curl
